version: "3"
services:
  as-is:
    build:
      context: .
      dockerfile: Base.Dockerfile
    ports:
      - 8081:8080
    environment:
      - PORT=8080
    volumes:
      - ./as-is:/usr/src/app
    entrypoint: ["yarn", "start"]
  fastify:
    build:
      context: .
      dockerfile: Base.Dockerfile
    ports:
      - 8082:8080
    environment:
      - PORT=8080
    volumes:
      - ./fastify:/usr/src/app
    entrypoint: ["yarn", "start"]
  fastify-cluster:
    build:
      context: .
      dockerfile: Base.Dockerfile
    ports:
      - 8083:8080
    environment:
      - PORT=8080
    volumes:
      - ./fastify-cluster:/usr/src/app
    entrypoint: ["yarn", "start"]